title: Patrick Molina
description: AI Student & Developer Portfolio
show_downloads: false
theme: jekyll-theme-minimal

# Personal info
email: patrickmolina458@gmail.com
github_username: patrickmolina1
linkedin_username: patrick-molina-270b81330

# Build settings
markdown: kramdown
