title: Patrick Molina
description: IT Student & Aspiring Developer | Passionate about Technology & Innovation
logo: /assets/img/profile.jpg
show_downloads: false
theme: jekyll-theme-cayman

# Social Links
github_username: patrickmolina1
linkedin_username: patrick-molina
email: your.email@example.com

# SEO
author: Patrick Molina
twitter:
  username: your_twitter_handle
  card: summary

# Analytics (optional)
google_analytics: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
