title: Patrick Molina
description: IT Student & Developer Portfolio
show_downloads: false
theme: jekyll-theme-minimal

# Personal info
email: your.email@example.com
github_username: patrickmolina1
linkedin_username: patrick-molina

# Build settings
markdown: kramdown
